"""create crimes, community_areas, and beats tables

Revision ID: 53897a515eb5
Revises: ce113c797d3f
Create Date: 2026-05-15 12:24:30.830740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '53897a515eb5'
down_revision: Union[str, None] = 'ce113c797d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('beat_number', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=8), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'beat_number', name='uq_beat_city_number')
    )
    op.create_index(op.f('ix_beats_city_id'), 'beats', ['city_id'], unique=False)
    op.create_table('community_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('area_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'area_number', name='uq_community_area_city_number')
    )
    op.create_index(op.f('ix_community_areas_city_id'), 'community_areas', ['city_id'], unique=False)
    op.create_table('crimes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('case_number', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('iucr', sa.String(length=8), nullable=True),
    sa.Column('primary_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('fbi_code', sa.String(length=8), nullable=True),
    sa.Column('block', sa.String(length=128), nullable=True),
    sa.Column('location_description', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('beat', sa.String(length=8), nullable=True),
    sa.Column('district', sa.String(length=8), nullable=True),
    sa.Column('ward', sa.Integer(), nullable=True),
    sa.Column('community_area', sa.Integer(), nullable=True),
    sa.Column('arrest', sa.Boolean(), nullable=True),
    sa.Column('domestic', sa.Boolean(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crimes_arrest'), 'crimes', ['arrest'], unique=False)
    op.create_index(op.f('ix_crimes_beat'), 'crimes', ['beat'], unique=False)
    op.create_index('ix_crimes_city_beat_year', 'crimes', ['city_id', 'beat', 'year'], unique=False)
    op.create_index(op.f('ix_crimes_city_id'), 'crimes', ['city_id'], unique=False)
    op.create_index('ix_crimes_city_type_year', 'crimes', ['city_id', 'primary_type', 'year'], unique=False)
    op.create_index('ix_crimes_city_year', 'crimes', ['city_id', 'year'], unique=False)
    op.create_index(op.f('ix_crimes_community_area'), 'crimes', ['community_area'], unique=False)
    op.create_index(op.f('ix_crimes_district'), 'crimes', ['district'], unique=False)
    op.create_index(op.f('ix_crimes_domestic'), 'crimes', ['domestic'], unique=False)
    op.create_index(op.f('ix_crimes_occurred_at'), 'crimes', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_crimes_primary_type'), 'crimes', ['primary_type'], unique=False)
    op.create_index(op.f('ix_crimes_year'), 'crimes', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crimes_year'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_primary_type'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_occurred_at'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_domestic'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_district'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_community_area'), table_name='crimes')
    op.drop_index('ix_crimes_city_year', table_name='crimes')
    op.drop_index('ix_crimes_city_type_year', table_name='crimes')
    op.drop_index(op.f('ix_crimes_city_id'), table_name='crimes')
    op.drop_index('ix_crimes_city_beat_year', table_name='crimes')
    op.drop_index(op.f('ix_crimes_beat'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_arrest'), table_name='crimes')
    op.drop_table('crimes')
    op.drop_index(op.f('ix_community_areas_city_id'), table_name='community_areas')
    op.drop_table('community_areas')
    op.drop_index(op.f('ix_beats_city_id'), table_name='beats')
    op.drop_table('beats')
    # ### end Alembic commands ###
