"""create beat_rollups table

Revision ID: 64023d052426
Revises: 53897a515eb5
Create Date: 2026-05-15 22:58:04.990061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64023d052426'
down_revision: Union[str, None] = '53897a515eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beat_rollups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('beat_number', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('primary_type', sa.String(length=64), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('arrest_count', sa.Integer(), nullable=False),
    sa.Column('domestic_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'beat_number', 'year', 'month', 'hour', 'day_of_week', 'primary_type', name='uq_beat_rollup_key')
    )
    op.create_index('ix_beat_rollups_city_beat_year', 'beat_rollups', ['city_id', 'beat_number', 'year'], unique=False)
    op.create_index(op.f('ix_beat_rollups_city_id'), 'beat_rollups', ['city_id'], unique=False)
    op.create_index('ix_beat_rollups_city_year_hour', 'beat_rollups', ['city_id', 'year', 'hour'], unique=False)
    op.create_index('ix_beat_rollups_primary_type', 'beat_rollups', ['primary_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_beat_rollups_primary_type', table_name='beat_rollups')
    op.drop_index('ix_beat_rollups_city_year_hour', table_name='beat_rollups')
    op.drop_index(op.f('ix_beat_rollups_city_id'), table_name='beat_rollups')
    op.drop_index('ix_beat_rollups_city_beat_year', table_name='beat_rollups')
    op.drop_table('beat_rollups')
    # ### end Alembic commands ###
